### ISSUE TITLE
1.2.8 authentication errors

### ISSUE THREAD

**Issue by midd33** [IndigoDomotics/indigo-ecobee-plugin#12]
since updating to version 1.2.8 I have continuously received the following error in my log:

 not authenticated to pyecobee yet; not initializing state of device (device number here)

I have tried reconfiguring my credentials by going to the ecobee site, deleting the current Indigo app, adding the app with the supplied pin. I then hit the refresh credentials.  The error keeps coming.

**Comment by FlyingDiver** [comment]
I had that happen once. I'm still looking into the root cause.  I think this is what fixed it.

First, ignore the PIN in the logs.  Only use the config dialog.  Second, don't delete the app from the Ecobee website.  Just authorize it again.

Open the config dialog.  Click the button to request a PIN.  Go to the Ecobee website.  Add the app again (don't delete) and enter that PIN.  The go back to the config dialog and refresh.

Does that work?

**Comment by midd33** [comment]
No it's still showing the error.  Did exactly as you instructed.  Request a pin from the plug in configuration.  Went to ecobee's site and added another indigo application without deleting the one already there.  Once it was added using the pin from the configuration, I refreshed my credentials.  The error appears every minute or so.

**Comment by FlyingDiver** [comment]
Please turn on debug logging (not detailed) and go through the process again.  Then post the plugin log.  It's in the log folder.  Not the main Indigo log.

**Comment by midd33** [comment]
Here's the log:
[ecobee.pdf](https://github.com/IndigoDomotics/indigo-ecobee-plugin/files/2345482/ecobee.pdf)

**Comment by FlyingDiver** [comment]
Hmm.  Nothing useful there.  This time try detailed debugging level.  And restart the plugin after you change the log level, then try the authentication.

And zip up the log and attach it.  No PDF please.

**Comment by midd33** [comment]
hmmm since I reloaded the plugin after changing the debugging level I haven't had any authentication errors.

**Comment by midd33** [comment]
no errors after 15 minutes.  I can't explain it since we had the electricity go out 2x yesterday for a few minutes so the plugin has been reloaded a few times.

**Comment by FlyingDiver** [comment]
Is that the first time you're reloaded it since the errors started?

Oops.  Just saw your last post.

**Comment by midd33** [comment]
no. we had some storms come through yesterday loss power 2x for a few minutes yesterday. I had to power on my mac mini each time.  Loss power one other time before that, a week ago.

**Comment by dnomode** [comment]
FYI: I got these errors today after starting up the server. Reloading the plugin seemed to fix the problem.

Started plugin "Ecobee 1.2.8"
   Ecobee                          Starting Ecobee
   Ecobee                          not authenticated to pyecobee yet; not initializing state of device 311012371611
   Ecobee                          added thermostat 311012371611
   Ecobee                          not authenticated to pyecobee yet; not initializing state of device GXB3
   Ecobee                          added remote sensor GXB3
   Ecobee                          not authenticated to pyecobee yet; not initializing state of device 311014354314
   Ecobee                          added thermostat 311014354314
   Ecobee                          not authenticated to pyecobee yet; not initializing state of device GXB3
   Ecobee                          not authenticated to pyecobee yet; not initializing state of device 311012371611
   Ecobee                          not authenticated to pyecobee yet; not initializing state of device 311014354314
   Trigger                         Ecobee Thermostat service down

**Comment by FlyingDiver** [comment]
This is the old version.  Will not be fixed.
