### ISSUE TITLE
All code gone? Download links don't work, all branches gone

### ISSUE THREAD

**Issue by jknobel** [IndigoDomotics/indigo-ecobee-plugin#15]
Hey guys,

Trying to get this plugin, but it looks like the repo has been emptied out? There are no branches pushed, and therefore none of the released versions can be downloaded.

**Comment by FlyingDiver** [comment]
That's because it doesn't work anymore.   The replacement is in beta testing at https://github.com/FlyingDiver/Indigo-Ecobee-2
