### ISSUE TITLE
Away Status not working

### ISSUE THREAD

**Issue by cutmoney** [IndigoDomotics/indigo-ecobee-plugin#2]
I'm seeing an error returned on the set away status command, it returns:

`Ecobee Error                    plugin does not define method setAwayStatus
`

**Comment by cutmoney** [comment]
Error on Resume All Programs, returns:

```
 Ecobee Error                    Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 371, in actionResumeProgram
AttributeError: 'Plugin' object has no attribute '_resumeProgram'
```

**Comment by FlyingDiver** [comment]
Will investigate.

**Comment by FlyingDiver** [comment]
Well, as far as I can tell, setAwayStatus was never implemented and never worked.  I'm taking the Action out.

I think I found the _resumeProgram error.  Fixed in next release.  Hopefully.
