### ISSUE TITLE
RequestStatusAll error

### ISSUE THREAD

**Issue by grwilde** [IndigoDomotics/indigo-ecobee-plugin#3]
Continually getting the following error

Error, received unimplemented action.thermostatAction:RequestStatusAll

**Comment by FlyingDiver** [comment]
Do you have a schedule or trigger that's doing a Request Status on the devices?

**Comment by grwilde** [comment]
Yes I do. It runs every 5 minutes to retrieve the air conditioning and heating status to accumulate daily amounts. It has worked with earlier versions.

**Comment by FlyingDiver** [comment]
Do you know what version you were previously running?  I don't see that implemented in 1.1.2 either, which is the version I started with.

**Comment by FlyingDiver** [comment]
Actually, I hope to heck you have a backup of your Indigo install so you can zip up your old plugin and attach it to this issue.  Because I went all the way back to v1.0.0 and there's no code in there to implement that call.

**Comment by grwilde** [comment]
I was using version 1.1.2 dated Nov. 29, 2017. I have attached a zipped copy of the plugin from a Time Machine backup.
This following is scheduled action I am performing every 5 minutes:

status request "Ecobee Thermostat"
insert state (timeleftminutes) for device "air conditioning timer" into variable:ac_dailymins
insert state (timeleftminutes) for device "heating timer" into variable:heating_dailymins
Then I execute a python script to determine daily ON time

It could be that the action really does not need the status request (I am not sure why I put it there unless I felt I needed it to get the most recent data). Anyway the previous plugin did not report an error even if it was not correctly handling the request. I will try just eliminating the status request from the scheduled item to see if that works OK.

[Ecobee (original).indigoPlugin.zip](https://github.com/IndigoDomotics/indigo-ecobee-plugin/files/2217348/Ecobee.original.indigoPlugin.zip)

**Comment by FlyingDiver** [comment]
D'oh.  I forgot that I added that error message in the latest version.  Before, the plugin was just silently ignoring the status request.  So your scheduled event to do a status request has been a no-op all along.
