### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by midd33** [IndigoDomotics/indigo-ecobee-plugin#4]
I've been receiving these messages in my Indigo Log at random intervals:

 Ecobee Error                    pyecobee: refreshing tokens; current authentication flag is True
   Ecobee Error                    pyecobee: authenticated after refreshing tokens, expires: 3599

**Comment by FlyingDiver** [comment]
The beta notes say that logging is still being worked on.  Those are expected.  I think they're gone in the latest beta release.
