### ISSUE TITLE
NoneType not iterable

### ISSUE THREAD

**Issue by rapamatic** [IndigoDomotics/indigo-ecobee-plugin#7]
I think this is the same error in the indigo forums, but I just got it this morning and wanted to post it here. I can confirm that it re-authenticates correctly, after manually restarting the plugin.

```
Aug 8, 2018, 8:14:31 AM
   Ecobee                          Error connecting to Ecobee.  Possible connectivity outage.
   Ecobee Error                    Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 163, in runConcurrentThread
  File "plugin.py", line 319, in updateAllDevices
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/Ecobee.indigoPlugin/Contents/Server Plugin/ecobee_devices.py", line 159, in updateServer
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/Ecobee.indigoPlugin/Contents/Server Plugin/ecobee_devices.py", line 56, in _get_thermostat_json
TypeError: 'NoneType' object is not iterable

   Ecobee Error                    plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

```

**Comment by FlyingDiver** [comment]
Thanks.  I'll see what I can do to suppress that error.

**Comment by rapamatic** [comment]
Also, the plugin seemed to hang after this error, not even trying to re-authenticate or throwing errors (turns out this happened before, and I didn't catch it until my error-checking script noticed that the devices hadn't been updated in a while). Maybe it makes sense to have a periodic action to restart the plugin to get around temporary errors like this (this would be something done on the indigo server, not the plugin)

**Comment by FlyingDiver** [comment]
That shouldn't be necessary if I can catch all the exceptions.  You could certainly do so as a work-around until the plugin is fixed.

This is some of the most confusing code I've ever worked with.  Sigh.

**Comment by rapamatic** [comment]
Yeah, the code for this plugin is pretty crazy. I've tried to clean it up over the years, but I am purely a hobbyist programmer, and I quickly got in over my head.

**Comment by FlyingDiver** [comment]
I think I've got a fix for that issue implemented.  Running it on my system now.  But it's hard to test because I can't create the error condition on-demand.

**Comment by rapamatic** [comment]
I'd be happy to test... I seem to get that error once or twice a day

**Comment by FlyingDiver** [comment]
Try https://github.com/IndigoDomotics/indigo-ecobee-plugin/releases/tag/1.2.5

**Comment by rapamatic** [comment]
Alright, I've got it running now, I'll report if I see anything.
